apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: default
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS execution_log (
        id SERIAL PRIMARY KEY,
        execution_time TIMESTAMP NOT NULL
    );