apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-postgres.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "custom-postgres.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "custom-postgres.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "custom-postgres.fullname" . }}-secret
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "custom-postgres.fullname" . }}-pvc
        - name: init-script-volume
          configMap:
            name: postgres-init-script