apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  labels:
    app: monitoring-grafana
spec:
  ports:
  - port: 80
    targetPort: grafana
    nodePort: 30082
  type: NodePort
  selector:
    app: monitoring-grafana
