replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

postgres:
  db: appdb
  user: appuser
  password: apppassword

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 2Gi